default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  database: dentis_code
  host: localhost
  username: root
  password: violet

development:
  <<: *default

test:
  <<: *default
  database: dentist_code_test

staging:
  <<: *default

production:
  <<: *default
