default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default
  database: ENV["DATABASE_NAME"]+"test"

staging:
  <<: *default

production:
  <<: *default
